### ISSUE TITLE
Private functions not authenticating

### ISSUE THREAD

**Issue by Bezowski** [naddison36/btc-markets#1]
Hi Nick,

I'm having trouble getting the private functions to authenticate. I'm using your examples.js file and have added my public and private API keys from BTC Markets to these lines: 

var key = process.argv[2] || 'your-api-key';
var secret = process.argv[3] || 'your-api-secret';

I've been trying the getAccountBalances function but it's only returning this data:

{"success":false,"errorCode":1,"errorMessage":"Authentication failed."}

I've checked the header information and the api key, timestamp and signature is there so maybe this is a problem on BTC Markets end?

Regards,

**Comment by naddison36** [comment]
I just testing using my prod keys and it worked for me. Probably best to email support@btcmarkets.net to see if they can see what the problem is at their end.

Nick

**Comment by Bezowski** [comment]
Ok thanks Nick.

**Comment by GenXau** [comment]
Hi,

I'm having the same issues. It seems intermittent. Sometimes it works sometimes it doesn't and my code hasn't changed at all. Support is hopeless, they don't respond (not what you want from an exchange). Any ideas?

{ [Authentication failed.: BTCMarkets.executeRequest() failed POST request to url https://api.btcmarkets.net/order/create with message /order/create
1470306288671
{"currency":"BTC","instrument":"ETC","price":524900,"volume":101700.00000000001,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Error message: Authentication failed.]
  jse_shortmsg: 'BTCMarkets.executeRequest() failed POST request to url https://api.btcmarkets.net/order/create with message /order/create\n1470306288671\n{"currency":"BTC","instrument":"ETC","price":524900,"volume":101700.00000000001,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Error message: Authentication failed.',
  jse_summary: 'BTCMarkets.executeRequest() failed POST request to url https://api.btcmarkets.net/order/create with message /order/create\n1470306288671\n{"currency":"BTC","instrument":"ETC","price":524900,"volume":101700.00000000001,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Error message: Authentication failed.',
  message: 'BTCMarkets.executeRequest() failed POST request to url https://api.btcmarkets.net/order/create with message /order/create\n1470306288671\n{"currency":"BTC","instrument":"ETC","price":524900,"volume":101700.00000000001,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Error message: Authentication failed.',
  name: 'Authentication failed.' }

**Comment by Bezowski** [comment]
Hi GenXau, I eventually got it working but unfortunately I can't remember how. It was something wrong with my code, not Nick's or BTC markets.

**Comment by GenXau** [comment]
Thanks for the reply, i'll keep hacking away. Authentication must be working as i can get my balances. Placing orders just plays up. Code was taken directly from examples.
Cheers,
