### ISSUE TITLE
POST requests (well createOrder) Not Authenticating

### ISSUE THREAD

**Issue by Ad0be** [naddison36/btc-markets#10]
Hi Nick.

First, thanks the package! Appreciate it.

An Issue I'm having (node.js) is that  .createOrder isn't working for me? and giving 'Authentication Failed'. The strange thing is the private GET based requests seem to be working ok (eg .getAccountBalances() works fine - so I don't think its issues with keys etc

Have you had any troubles with this recently? or are you able to point me in the right direction?

I get:

> Authentication failed.: failed POST request to url https://api.btcmarkets.net/order/create with message /order/create
1520155928444
{"currency":"AUD","instrument":"BTC","price":"1449006000000","volume":"500000","orderSide":"Bid","ordertype":"Limit","clientRequestId":"10001"}. Success: false. Error message: Authentication failed.

to me it leaves two possible problems the order/format of the POST variables or the integer format for prices. 

I was looking in the package index.js and noticed:

`const options = {
            url: this.server + path,
            method: method,
            headers: headers,
            timeout: this.timeout,
            json: params
        };`

could this have anything to do with the params in the options does this need to be stringified or similar? (excuse the javascript ignorance)

Cheers,

Kane.

**Comment by naddison36** [comment]
Price and Volume need to be a number and not a string.
Let me know how you go
Nick

**Comment by Ad0be** [comment]
Thanks Nick. That did the trick. (*facepalm*)

**Comment by naddison36** [comment]
That's why I like TypeScript :-)
Good to hear it's all working now

**Comment by Ad0be** [comment]
I will check out TypeScript!. Though Ive just started learning Javascript (a couple of days ago) so I thought it a bit too much to start with :) I was using Swift but had some fundamental crypto issues :/
