### ISSUE TITLE
Client for streamed events over websockets

### ISSUE THREAD

**Issue by naddison36** [naddison36/btc-markets#6]
https://github.com/BTCMarkets/API/wiki/websocket

**Comment by j03w** [comment]
I don't think you really need to implement that as a part of this module. Their websocket doesn't require auth so there isn't much point in adding extra dependencies or complexity to this.

https://jsbin.com/vawosodixe/edit?html,js,output

**Comment by naddison36** [comment]
Wow, I didn't realise it was that easy. If they add authenticated websockets then it'll make sense to wrap.
