### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by stramec** [naddison36/btc-markets#8]
Hi There

Firstly thanks for taking the time to create this, saved an awful lot of work for the rest of us.

I'm having a couple of issues, which I'll split out so they are easier to track.

I'm getting an authentication error on the createOrder method. 
I'm confident my authentication keys are working as all of the GET account / transaction history etc, return without complaint. 

I can't see anything wrong with the code for creating the nonce and signature, and although I can't find in the BTCMarkets API Doco anywhere that says how to get the server time, based on the response timestamps and a bit of network lag I can't be more than half a second out, so I don't think it's a time issue.

Just wondered if you had any suggestions on what could be the issue or how to troubleshoot it further?

**Comment by naddison36** [comment]
Does the following from the examples work for you?
```JS
        // limit buy order for of 0.001 ETH at 500 AUD
        const limitOrder = await client.createOrder("ETH", "AUD", 500 * BTCMarkets.numberConverter, 0.001 * BTCMarkets.numberConverter, 'Bid', 'Limit', "10001");
        console.log(`Limit order: ${JSON.stringify(limitOrder)}`);
```

It's working for me at the moment which includes version 1.0.5 that I just published to fix the withdrawHistory issue.

**Comment by stramec** [comment]
Yes mate, not sure what was going on there, but seems to be working fine after the update. Thanks for getting back to me so quickly.

**Comment by naddison36** [comment]
Good to hear it's now working
