### ISSUE TITLE
withdrawHistory should be a GET request

### ISSUE THREAD

**Issue by stramec** [naddison36/btc-markets#9]
Hi,

Just tried to run this from the examples: 
  const withdrawHistory = await client.withdrawHistory(null, null, null);
  console.log(`Withdrawal history: ${JSON.stringify(withdrawHistory)}`);

I'm afraid it returns the following.
 message: 'HTTP status code 405 returned from POST request to url https://api.btcmarkets.net/fundtransfer/history with message /fundtransfer/history\n1517716055380\n{"limit":null,"since":null,"indexForward":null}. Status message: Method Not Allowed',
  name: '405' }

I think this should probably be a GET request not a POST.

Cheers

**Comment by naddison36** [comment]
You are correct, withdrawHistory should be a POST. The signature is also different as per the documentation https://github.com/BTCMarkets/API/wiki/Fund-Transfer-API#fund-transfer-history

The two withdrawHistory calls in the examples are working for me now so please try again with version 1.0.5
